#!/bin/sh

# Create symlinks
ln -sT "$PWD/bin"			"$HOME/.local/bin"
ln -sT "$PWD/gitconfig"		"$HOME/.gitconfig"
ln -sT "$PWD/profile"		"$HOME/.profile"
ln -sT "$PWD/sfeedrc"		"$XDG_CONFIG_HOME/sfeedrc"
ln -sT "$PWD/fish"			"$XDG_CONFIG_HOME/fish"
ln -sT "$PWD/mpd.conf"		"$XDG_CONFIG_HOME/mpd"
ln -sT "$PWD/ncmcpp"		"$XDG_CONFIG_HOME/ncmcpp"
ln -sT "$PWD/nvim"			"$XDG_CONFIG_HOME/nvim"
ln -sT "$PWD/sxhkdrc"		"$XDG_CONFIG_HOME/sxhkd"
ln -sT "$PWD/youtube-dl"	"$XDG_CONFIG_HOME/youtube-dl"
ln -sT "$PWD/zathura"		"$XDG_CONFIG_HOME/zathura"
