#!/bin/sh

# Set config home temporarily if unset
if [ -z $XDG_CONFIG_HOME ]; then
	export XDG_CONFIG_HOME=$HOME/.config
fi

dot() {
	# Usage: dot "from" "to"
	printf '%s -> %s ' $1 $2
	# Return if dot already exits
	if [ -e $2 ]; then
		printf 'Already exists\n'
	# Otherwise create it
	else
		dir="$(dirname $2)"
		mkdir -p $dir
		ln -sT $1 $2
		printf 'Created\n'
	fi
}

# Create symlinks
dot "$PWD/bin"			"$HOME/.local/bin"
dot "$PWD/gitconfig"	"$HOME/.gitconfig"
dot "$PWD/profile"		"$HOME/.profile"
dot "$PWD/ssh"			"$HOME/.ssh"
dot "$PWD/fish"			"$XDG_CONFIG_HOME/fish"
dot "$PWD/fnott.ini"	"$XDG_CONFIG_HOME/fnott/fnott.ini"
dot "$PWD/foot.ini"		"$XDG_CONFIG_HOME/foot/foot.ini"
dot "$PWD/lynx"			"$XDG_CONFIG_HOME/lynx"
dot "$PWD/mpd.conf"		"$XDG_CONFIG_HOME/mpd/mpd.conf"
dot "$PWD/mpv"			"$XDG_CONFIG_HOME/mpv"
dot "$PWD/ncmpcpp"		"$XDG_CONFIG_HOME/ncmpcpp"
dot "$PWD/nvim"			"$XDG_CONFIG_HOME/nvim"
dot "$PWD/sfeedrc"		"$XDG_CONFIG_HOME/sfeedrc"
dot "$PWD/sway"			"$XDG_CONFIG_HOME/sway/config"
dot "$PWD/sxhkdrc"		"$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
dot "$PWD/ytdl"			"$XDG_CONFIG_HOME/ytdl"
dot "$PWD/zathura"		"$XDG_CONFIG_HOME/zathura"
