abbr -a Install 'doas make clean install; git clean -f .'
abbr -a Patch 'patch -p1 <'
abbr -a cb 'cmake --build'
abbr -a cfg '~/.local/bin/config'
abbr -a ct 'ctags -R'
abbr -a fcc 'fc-cache -frv'
abbr -a fcg 'fc-list | grep -i'
abbr -a fcl 'fc-list | less'
abbr -a p 'pass'
abbr -a pIP 'curl https://ipinfo.io/ip'
abbr -a sfc 'sfeed_curses ~/.local/share/sfeed/feeds/*'
abbr -a sfu 'sfeed_update ~/.config/sfeedrc'
abbr -a todo 'grep TODO *'
abbr -a v 'vim'
abbr -a ncmpc 'ncmpc --password (pass cosmos/mpd)'
