abbr -a ga 'git add'
abbr -a gb 'git branch'
abbr -a gbd 'git branch -D'
abbr -a gc 'git commit -S -v'
abbr -a gcb 'git checkout -b'
abbr -a gcl 'git clone'
abbr -a gco 'git checkout'
abbr -a gd 'git diff'
abbr -a gdc 'git diff --cached'
abbr -a gi 'git init'
abbr -a gl 'git log'
abbr -a glo 'git log --oneline'
abbr -a gm 'git merge'
abbr -a gp 'git push'
abbr -a gpl 'git pull'
abbr -a gpu 'git push --set-upstream'
abbr -a gr 'git restore'
abbr -a gra 'git remote add'
abbr -a grap 'git remote add pi git@jstnas.com:'
abbr -a grm 'git rm'
abbr -a grmc 'git rm --cached'
abbr -a grs 'git restore --staged'
abbr -a gs 'git status'
abbr -a gsw 'git switch'
abbr -a gswc 'git switch -c'
abbr -a gt 'cd (git rev-parse --show-toplevel)'
