abbr -a venv 'python -m venv --upgrade-deps .venv'
abbr -a venvs 'source .venv/bin/activate.fish'
abbr -a pipl 'python -m pip list'
abbr -a pipi 'python -m pip install --upgrade'
abbr -a pipu 'python -m pip uninstall'
