#!/bin/sh

xrdb ~/.config/Xresources

# audio
pipewire &
pipewire-pulse &
wireplumber &

# launch programs
dunst &
dwmblocks &
picom --experimental-backends &
sxhkd &
xbanish -t 3 &
low_battery &

# wallpaper
wall-skeen &

# start window manager
exec dwm
