set ai nocp hid ru sc sm nosol wmnu
set noeb
set nu rnu
set ic scs
set is hls
set bs=2 ls=2 shm=at ww=<,>,h,l
set noet ts=4 sts=4 sw=4
set list lcs=tab:>-,trail:.
set vif=~/.vim/viminfo
syntax on
filetype plugin indent on

set completeopt-=preview
set noswapfile
set complete=.,w,b,u,t,i,kspell
set path+=**
let mapleader=" "

" File browser.
let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
"let g:netrw_winsize=25
"let g:netrw_preview=1

" Remaps.
" Command without shift
nnoremap ; :
nnoremap : ;
" Window splits.
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
" Toggle highlight search
nnoremap <F4> :noh<CR>

" Colourscheme.
colorscheme dim
set background=dark

" Lightline.
let g:lightline = {'colorscheme': 'dim'}
set noshowmode

" Hightlight column.
set colorcolumn=81
highlight ColorColumn ctermbg=4

set shell=/bin/sh
