#!/bin/sh

. ./deploy/base

heading "linux"

dot "$PWD/fish"			"$XDG_CONFIG_HOME/fish"
dot "$PWD/nvim"			"$XDG_CONFIG_HOME/nvim"
dot "$PWD/profile"		"$HOME/.profile"
dot "$PWD/sfeedrc"		"$XDG_CONFIG_HOME/sfeedrc"
dot "$PWD/tmux.conf"	"$XDG_CONFIG_HOME/tmux/tmux.conf"
dot "$PWD/aria2.conf"	"$XDG_CONFIG_HOME/aria2/aria2.conf"
