#!/bin/sh

. ./deploy/base

heading "linux"

dot "$PWD/fish"			"$XDG_CONFIG_HOME/fish"
dot "$PWD/nvim"			"$XDG_CONFIG_HOME/nvim"
dot "$PWD/profile"		"$HOME/.profile"
dot "$PWD/profiles"		"$XDG_CONFIG_HOME/profiles"
dot "$PWD/sfeedrc"		"$XDG_CONFIG_HOME/sfeedrc"
dot "$PWD/msmtprc"		"$XDG_CONFIG_HOME/msmtp/config"
