#!/bin/sh

. ./deploy/arch
. ./deploy/bin
. ./deploy/fontconfig
. ./deploy/global
. ./deploy/graphical
. ./deploy/linux
. ./deploy/lynx
. ./deploy/mpd
. ./deploy/mpv
. ./deploy/newsboat
. ./deploy/x11
