#!/bin/sh

. ./deploy/base

heading "wayland"

dot "$PWD/fnott.ini"	"$XDG_CONFIG_HOME/fnott/fnott.ini"
dot "$PWD/foot.ini"		"$XDG_CONFIG_HOME/foot/foot.ini"
dot "$PWD/i3blocks"		"$XDG_CONFIG_HOME/i3blocks/config"
dot "$PWD/kanshi"		"$XDG_CONFIG_HOME/kanshi"
dot "$PWD/mako"			"$XDG_CONFIG_HOME/mako/config"
dot "$PWD/mpv"			"$XDG_CONFIG_HOME/mpv"
dot "$PWD/ncmpcpp"		"$XDG_CONFIG_HOME/ncmpcpp"
dot "$PWD/sway"			"$XDG_CONFIG_HOME/sway/config"
dot "$PWD/zathura"		"$XDG_CONFIG_HOME/zathura"
