#!/bin/sh

. ./deploy/base

heading "x11"

dot "$PWD/x11/sxrc"			"$XDG_CONFIG_HOME/sx/sxrc"
dot "$PWD/x11/sxhkdrc"		"$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
dot "$PWD/x11/picom.conf"	"$XDG_CONFIG_HOME/picom/picom.conf"
