#!/bin/sh

. ./deploy/base

heading "x11"

dot "$PWD/profile.d/x11.sh"	"$XDG_CONFIG_HOME/profile.d/x11.sh"
dot "$PWD/x11/dunstrc"		"$XDG_CONFIG_HOME/dunst/dunstrc"
dot "$PWD/x11/picom.conf"	"$XDG_CONFIG_HOME/picom/picom.conf"
dot "$PWD/x11/sxhkdrc"		"$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
dot "$PWD/x11/sxrc"			"$XDG_CONFIG_HOME/sx/sxrc"
